apiVersion: v2
name: gpu-operator
version: v1.0.0-devel
kubeVersion: ">= 1.16.0-0"
description: XDXCT GPU Operator creates/configures/manages GPUs Services
appVersion: "devel"
sources:
- https://github.com/NVIDIA/gpu-operator
home: https://docs.xdxct.com/datacenter/cloud-native/gpu-operator/overview.html
keywords:
  - gpu
  - cuda
  - compute
  - operator
  - deep learning
  - monitoring
  - tesla

dependencies:
  - name: node-feature-discovery
    version: v0.13.1
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    condition: nfd.enabled
