apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xdxct-device-plugin
  namespace: "FILLED BY THE OPERATOR"
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - gpu-operator-privileged
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch

