apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xdxct-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xdxct-device-plugin
subjects:
- kind: ServiceAccount
  name: xdxct-device-plugin
  namespace: "FILLED BY THE OPERATOR"
