apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xdxct-container-toolkit
  namespace: "FILLED BY THE OPERATOR"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xdxct-container-toolkit
subjects:
- kind: ServiceAccount
  name: xdxct-container-toolkit
  namespace: "FILLED BY THE OPERATOR"
