apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: xdxct-container-toolkit-daemonset
  name: xdxct-container-toolkit-daemonset
  namespace: "FILLED BY THE OPERATOR"
spec:
  selector:
    matchLabels:
      app: xdxct-container-toolkit-daemonset
  template:
    metadata:
      labels:
        app: xdxct-container-toolkit-daemonset
    spec:
      nodeSelector:
        xdxct.com/gpu.deploy.container-toolkit: "true"
      tolerations:
        - key: xdxct.com/gpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
      serviceAccountName: xdxct-container-toolkit
      hostPID: true
      # initContainers:
      # - name: driver-validation
      #   image: "FILLED BY THE OPERATOR"
      #   imagePullPolicy: IfNotPresent
      #   command: ['sh', '-c']
      #   args: ["nvidia-validator"]
      #   env:
      #     - name: WITH_WAIT
      #       value: "true"
      #     - name: COMPONENT
      #       value: driver
      #   securityContext:
      #     privileged: true
      #     seLinuxOptions:
      #       level: "s0"
      #   volumeMounts:
      #     - name: driver-install-path
      #       mountPath: /run/nvidia/driver
      #       mountPropagation: HostToContainer
      #     - name: run-nvidia-validations
      #       mountPath: /run/nvidia/validations
      #       mountPropagation: Bidirectional
      #     - name: host-root
      #       mountPath: /host
      #       readOnly: true
      #       mountPropagation: HostToContainer
      #     - name: host-dev-char
      #       mountPath: /host-dev-char
      containers:
      - image: "FILLED BY THE OPERATOR"
        command: ["/bin/bash", "-c"]
        args:
          - /bin/entrypoint.sh
        env:
        - name: ROOT
          value: "/usr/local/xdxct"
        - name: RUNTIME_ARGS
          value: ""
        - name: XDXCT_CONTAINER_RUNTIME_MODES_CDI_DEFAULT_KIND
          value: "management.xdxct.com/gpu"
        - name: XDXCT_VISIBLE_DEVICES
          value: "void"
        imagePullPolicy: IfNotPresent
        name: xdxct-container-toolkit-ctr
        securityContext:
          privileged: true
          seLinuxOptions:
            level: "s0"
        volumeMounts:
          - name: xdxct-container-toolkit-entrypoint
            readOnly: true
            mountPath: /bin/entrypoint.sh
            subPath: entrypoint.sh
          - name: xdxct-run-path
            mountPath: /run/xdxct
            mountPropagation: Bidirectional
          - name: toolkit-install-dir
            mountPath: /usr/local/xdxct
          - name: host-daemon-config
            mountPath: /etc/docker
          - name: host-docker-socket
            mountPath: /var/run
      volumes:
        - name: xdxct-container-toolkit-entrypoint
          configMap:
            name: xdxct-container-toolkit-entrypoint
            defaultMode: 448
        - name: xdxct-run-path
          hostPath:
            path: /run/xdxct
            type: DirectoryOrCreate
        - name: host-daemon-config
          hostPath:
            path: /etc/docker
        - name: toolkit-install-dir
          hostPath:
            path: /usr/local/xdxct
        - name: host-docker-socket
          hostPath:
            path: /var/run