apiVersion: xdxct.com/v1
kind: ClusterPolicy
metadata:
  name: cluster-policy
  labels:
    {{- include "gpu-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: "gpu-operator"
  {{- if .Values.operator.cleanupCRD }}
  # CR cleanup is handled during pre-delete hook
  # Add below annotation so that helm doesn't attempt to cleanup CR twice
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  operator:
    {{- if .Values.operator.defaultRuntime }}
    defaultRuntime: {{ .Values.operator.defaultRuntime }}
    {{- end }}
    {{- if .Values.operator.runtimeClass }}
    runtimeClass: {{ .Values.operator.runtimeClass }}
    {{- end }}
    {{- if .Values.operator.defaultGPUMode }}
    defaultGPUMode: {{ .Values.operator.defaultGPUMode }}
    {{- end }}
    {{- if .Values.operator.initContainer }}
    initContainer:
      {{- if .Values.operator.initContainer.repository }}
      repository: {{ .Values.operator.initContainer.repository }}
      {{- end }}
      {{- if .Values.operator.initContainer.image }}
      image: {{ .Values.operator.initContainer.image }}
      {{- end }}
      {{- if .Values.operator.initContainer.version }}
      version: {{ .Values.operator.initContainer.version | quote }}
      {{- end }}
      {{- if .Values.operator.initContainer.imagePullPolicy }}
      imagePullPolicy: {{ .Values.operator.initContainer.imagePullPolicy }}
      {{- end }}
      {{- if .Values.operator.initContainer.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.operator.initContainer.imagePullSecrets | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.operator.use_ocp_driver_toolkit }}
    use_ocp_driver_toolkit: {{ .Values.operator.use_ocp_driver_toolkit }}
    {{- end }}
  daemonsets:
    labels:
      {{- include "gpu-operator.operand-labels" . | nindent 6 }}
    {{- if .Values.daemonsets.annotations }}
    annotations: {{ toYaml .Values.daemonsets.annotations | nindent 6 }}
    {{- end }}
    {{- if .Values.daemonsets.tolerations }}
    tolerations: {{ toYaml .Values.daemonsets.tolerations | nindent 6 }}
    {{- end }}
    {{- if .Values.daemonsets.priorityClassName }}
    priorityClassName: {{ .Values.daemonsets.priorityClassName }}
    {{- end }}
    {{- if .Values.daemonsets.updateStrategy }}
    updateStrategy: {{ .Values.daemonsets.updateStrategy }}
    {{- end }}
    {{- if .Values.daemonsets.rollingUpdate }}
    rollingUpdate:
      maxUnavailable: {{ .Values.daemonsets.rollingUpdate.maxUnavailable | quote }}
    {{- end }}
  validator:
    {{- if .Values.validator.repository }}
    repository: {{ .Values.validator.repository }}
    {{- end }}
    {{- if .Values.validator.image }}
    image: {{ .Values.validator.image }}
    {{- end }}
    version: {{ .Values.validator.version | default .Chart.AppVersion | quote }}
    {{- if .Values.validator.imagePullPolicy }}
    imagePullPolicy: {{ .Values.validator.imagePullPolicy }}
    {{- end }}
    {{- if .Values.validator.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.validator.imagePullSecrets | nindent 8 }}
    {{- end }}
    {{- if .Values.validator.resources }}
    resources: {{ toYaml .Values.validator.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.validator.env }}
    env: {{ toYaml .Values.validator.env | nindent 6 }}
    {{- end }}
    {{- if .Values.validator.args }}
    args: {{ toYaml .Values.validator.args | nindent 6 }}
    {{- end }}
    {{- if .Values.validator.plugin }}
    plugin:
      {{- if .Values.validator.plugin.env }}
      env: {{ toYaml .Values.validator.plugin.env | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.validator.driver }}
    driver:
      {{- if .Values.validator.driver.env }}
      env: {{ toYaml .Values.validator.driver.env | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if .Values.validator.toolkit }}
    toolkit:
      {{- if .Values.validator.toolkit.env }}
      env: {{ toYaml .Values.validator.toolkit.env | nindent 8 }}
      {{- end }}
    {{- end }}
  
  psp:
    enabled: {{ .Values.psp.enabled }}
  psa:
    enabled: {{ .Values.psa.enabled }}
  cdi:
    enabled: {{ .Values.cdi.enabled }}
    default: {{ .Values.cdi.default }}
  driver:
    enabled: {{ .Values.driver.enabled }}
    usePrecompiled: {{ .Values.driver.usePrecompiled }}
    {{- if .Values.driver.repository }}
    repository: {{ .Values.driver.repository }}
    {{- end }}
    {{- if .Values.driver.image }}
    image: {{ .Values.driver.image }}
    {{- end }}
    {{- if .Values.driver.version }}
    version: {{ .Values.driver.version | quote }}
    {{- end }}
    {{- if .Values.driver.imagePullPolicy }}
    imagePullPolicy: {{ .Values.driver.imagePullPolicy }}
    {{- end }}
    {{- if .Values.driver.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.driver.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.startupProbe }}
    startupProbe: {{ toYaml .Values.driver.startupProbe | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.livenessProbe }}
    livenessProbe: {{ toYaml .Values.driver.livenessProbe | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.readinessProbe }}
    readinessProbe: {{ toYaml .Values.driver.readinessProbe | nindent 6 }}
    {{- end }}
    rdma:
      enabled: {{ .Values.driver.rdma.enabled }}
      useHostMofed: {{ .Values.driver.rdma.useHostMofed }}
    manager:
      {{- if .Values.driver.manager.repository }}
      repository: {{ .Values.driver.manager.repository }}
      {{- end }}
      {{- if .Values.driver.manager.image }}
      image: {{ .Values.driver.manager.image }}
      {{- end }}
      {{- if .Values.driver.manager.version }}
      version: {{ .Values.driver.manager.version | quote }}
      {{- end }}
      {{- if .Values.driver.manager.imagePullPolicy }}
      imagePullPolicy: {{ .Values.driver.manager.imagePullPolicy }}
      {{- end }}
      {{- if .Values.driver.manager.env }}
      env: {{ toYaml .Values.driver.manager.env | nindent 8 }}
      {{- end }}
    {{- if .Values.driver.repoConfig }}
    repoConfig: {{ toYaml .Values.driver.repoConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.certConfig }}
    certConfig: {{ toYaml .Values.driver.certConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.licensingConfig }}
    licensingConfig: {{ toYaml .Values.driver.licensingConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.virtualTopology }}
    virtualTopology: {{ toYaml .Values.driver.virtualTopology | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.kernelModuleConfig }}
    kernelModuleConfig: {{ toYaml .Values.driver.kernelModuleConfig | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.resources }}
    resources: {{ toYaml .Values.driver.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.env }}
    env: {{ toYaml .Values.driver.env | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.args }}
    args: {{ toYaml .Values.driver.args | nindent 6 }}
    {{- end }}
    {{- if .Values.driver.upgradePolicy }}
    upgradePolicy:
      autoUpgrade: {{ .Values.driver.upgradePolicy.autoUpgrade | default false }}
      maxParallelUpgrades: {{ .Values.driver.upgradePolicy.maxParallelUpgrades | default 0 }}
      maxUnavailable : {{ .Values.driver.upgradePolicy.maxUnavailable | default "25%" }}
      waitForCompletion:
        timeoutSeconds: {{ .Values.driver.upgradePolicy.waitForCompletion.timeoutSeconds }}
        {{- if .Values.driver.upgradePolicy.waitForCompletion.podSelector }}
        podSelector: {{ .Values.driver.upgradePolicy.waitForCompletion.podSelector }}
        {{- end }}
      podDeletion:
        force: {{ .Values.driver.upgradePolicy.gpuPodDeletion.force | default false }}
        timeoutSeconds: {{ .Values.driver.upgradePolicy.gpuPodDeletion.timeoutSeconds }}
        deleteEmptyDir: {{ .Values.driver.upgradePolicy.gpuPodDeletion.deleteEmptyDir | default false }}
      drain:
        enable: {{ .Values.driver.upgradePolicy.drain.enable | default false }}
        force: {{ .Values.driver.upgradePolicy.drain.force | default false }}
        {{- if .Values.driver.upgradePolicy.drain.podSelector }}
        podSelector: {{ .Values.driver.upgradePolicy.drain.podSelector }}
        {{- end }}
        timeoutSeconds: {{ .Values.driver.upgradePolicy.drain.timeoutSeconds }}
        deleteEmptyDir: {{ .Values.driver.upgradePolicy.drain.deleteEmptyDir | default false}}
    {{- end }}
  toolkit:
    enabled: {{ .Values.toolkit.enabled }}
    {{- if .Values.toolkit.repository }}
    repository: {{ .Values.toolkit.repository }}
    {{- end }}
    {{- if .Values.toolkit.image }}
    image: {{ .Values.toolkit.image }}
    {{- end }}
    {{- if .Values.toolkit.version }}
    version: {{ .Values.toolkit.version | quote }}
    {{- end }}
    {{- if .Values.toolkit.imagePullPolicy }}
    imagePullPolicy: {{ .Values.toolkit.imagePullPolicy }}
    {{- end }}
    {{- if .Values.toolkit.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.toolkit.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.toolkit.resources }}
    resources: {{ toYaml .Values.toolkit.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.toolkit.env }}
    env: {{ toYaml .Values.toolkit.env | nindent 6 }}
    {{- end }}
    {{- if .Values.toolkit.installDir }}
    installDir: {{ .Values.toolkit.installDir }}
    {{- end }}
  devicePlugin:
    enabled: {{ .Values.devicePlugin.enabled }}
    {{- if .Values.devicePlugin.repository }}
    repository: {{ .Values.devicePlugin.repository }}
    {{- end }}
    {{- if .Values.devicePlugin.image }}
    image: {{ .Values.devicePlugin.image }}
    {{- end }}
    {{- if .Values.devicePlugin.version }}
    version: {{ .Values.devicePlugin.version | quote }}
    {{- end }}
    {{- if .Values.devicePlugin.imagePullPolicy }}
    imagePullPolicy: {{ .Values.devicePlugin.imagePullPolicy }}
    {{- end }}
    {{- if .Values.devicePlugin.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.devicePlugin.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.devicePlugin.resources }}
    resources: {{ toYaml .Values.devicePlugin.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.devicePlugin.env }}
    env: {{ toYaml .Values.devicePlugin.env | nindent 6 }}
    {{- end }}
    {{- if .Values.devicePlugin.args }}
    args: {{ toYaml .Values.devicePlugin.args | nindent 6 }}
    {{- end }}
    {{- if .Values.devicePlugin.config.name }}
    config:
      name: {{ .Values.devicePlugin.config.name }}
      default: {{ .Values.devicePlugin.config.default }}
    {{- end }}
  nodeStatusExporter:
    enabled: {{ .Values.nodeStatusExporter.enabled }}
    {{- if .Values.nodeStatusExporter.repository }}
    repository: {{ .Values.nodeStatusExporter.repository }}
    {{- end }}
    {{- if .Values.nodeStatusExporter.image }}
    image: {{ .Values.nodeStatusExporter.image }}
    {{- end }}
    version: {{ .Values.nodeStatusExporter.version | default .Chart.AppVersion | quote }}
    {{- if .Values.nodeStatusExporter.imagePullPolicy }}
    imagePullPolicy: {{ .Values.nodeStatusExporter.imagePullPolicy }}
    {{- end }}
    {{- if .Values.nodeStatusExporter.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.nodeStatusExporter.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.nodeStatusExporter.resources }}
    resources: {{ toYaml .Values.nodeStatusExporter.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.nodeStatusExporter.env }}
    env: {{ toYaml .Values.nodeStatusExporter.env | nindent 6 }}
    {{- end }}
    {{- if .Values.nodeStatusExporter.args }}
    args: {{ toYaml .Values.nodeStatusExporter.args | nindent 6 }}
    {{- end }}
  gfd:
    enabled: {{ .Values.gfd.enabled }}
    {{- if .Values.gfd.repository }}
    repository: {{ .Values.gfd.repository }}
    {{- end }}
    {{- if .Values.gfd.image }}
    image: {{ .Values.gfd.image }}
    {{- end }}
    {{- if .Values.gfd.version }}
    version: {{ .Values.gfd.version | quote }}
    {{- end }}
    {{- if .Values.gfd.imagePullPolicy }}
    imagePullPolicy: {{ .Values.gfd.imagePullPolicy }}
    {{- end }}
    {{- if .Values.gfd.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.gfd.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.gfd.resources }}
    resources: {{ toYaml .Values.gfd.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.gfd.env }}
    env: {{ toYaml .Values.gfd.env | nindent 6 }}
    {{- end }}
    {{- if .Values.gfd.args }}
    args: {{ toYaml .Values.gfd.args | nindent 6 }}
    {{- end }}
