apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-operator
  labels:
    # -: 删除不必要的空白字符 nindent: 头缩进4格
    {{- include "gpu-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: "gpu-operator"
