apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nvidia-node-status-exporter
  name: nvidia-node-status-exporter
  namespace: "FILLED BY THE OPERATOR"
  annotations:
    openshift.io/scc: nvidia-node-status-exporter
spec:
  selector:
    matchLabels:
      app: nvidia-node-status-exporter
  template:
    metadata:
      labels:
        app: nvidia-node-status-exporter
    spec:
      nodeSelector:
        xdxct.com/gpu.deploy.node-status-exporter: "true"
      tolerations:
        - key: xdxct.com/gpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
      serviceAccountName: nvidia-node-status-exporter
      containers:
      - image: "FILLED BY THE OPERATOR"
        imagePullPolicy: Always
        name: nvidia-node-status-exporter
        command: [nvidia-validator]
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        - name: COMPONENT
          value: metrics
        - name: METRICS_PORT
          value: "8000"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: node-status
          containerPort: 8000
        securityContext:
          privileged: true
        volumeMounts:
          - name: run-nvidia
            mountPath: "/run/nvidia"
            mountPropagation: HostToContainer
          - name: host-root
            mountPath: /host
            readOnly: true
            mountPropagation: HostToContainer
      volumes:
        - name: run-nvidia
          hostPath:
            path: /run/nvidia
            type: Directory
        - name: host-root
          hostPath:
            path: /
